# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{uid_attribute}
  s.version = "0.2.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Belt"]
  s.date = %q{2010-05-05}
  s.description = %q{Some projects are confined by regulations (or requirements) that demand data can not be used to identify individuals. In such cases data must be scrubbed i.e. identifiable object names must be removed before unauthorized users can see said data. For example, when a developer needs to recreate a bug on their own system that was reported by a customer using customer-specific data.

One method to do this is to use globally unique identifiers within the system to identify any given object.}
  s.email = %q{Paul Belt}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "lib/uid_attribute.rb",
     "test/uid_attribute_test.rb",
     "uid_attribute.gemspec"
  ]
  s.homepage = %q{http://github.com/belt/uid_attribute}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{uid_attribute}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{machina to automatically generate UUIDs upon object instantiation.}
  s.test_files = [
    "test/uid_attribute_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<uuidtools>, [">= 2.1.1"])
    else
      s.add_dependency(%q<uuidtools>, [">= 2.1.1"])
    end
  else
    s.add_dependency(%q<uuidtools>, [">= 2.1.1"])
  end
end

